daily

diff --git a/cc.leetcode/run b/cc.leetcode/run
--- a/cc.leetcode/run
+++ b/cc.leetcode/run
@@ -6,8 +6,15 @@ test $1 != "" || {
   exit 1
 }
 
+(scl -l | grep -q devtoolset-7) || {
+  echo "devtoolset-7 required"
+  exit 1
+}
+
 name=$(basename $1 .cc)
-(g++ -o $name $name.cc -std=c++0x -g -Wall && ./$name) && {
+scl enable devtoolset-7 bash <<EOF
+(g++ -o $name $name.cc -std=c++1z -g -Wall && ./$name) && {
   echo "OK"
   test -f $name && rm $name
 }
+EOF
